Support non-string exports like https://github.com/dazuaz/responsive-loader
Module https://github.com/dazuaz/responsive-loader exports images as an object like { src: "", srcSet: ", ..}. Helmet expects a string and therefore crushes as: TypeError: tag[primaryAttributeKey].toLowerCase is not a function